/**
 * AI 工具数据库
 * 每个工具包含：名称、简介、分类、链接、图标、评分、价格、标签、是否新上线
 */

const CATEGORIES = [
    { id: 'all', name: '全部', icon: '🌐' },
    { id: 'chat', name: '对话聊天', icon: '💬' },
    { id: 'writing', name: '写作文案', icon: '✍️' },
    { id: 'image', name: '图像生成', icon: '🎨' },
    { id: 'video', name: '视频制作', icon: '🎬' },
    { id: 'audio', name: '音频音乐', icon: '🎵' },
    { id: 'coding', name: '编程开发', icon: '💻' },
    { id: 'design', name: '设计工具', icon: '🖌️' },
    { id: 'productivity', name: '效率办公', icon: '📊' },
    { id: 'education', name: '学习教育', icon: '📚' },
    { id: 'marketing', name: '营销推广', icon: '📢' },
];

const AI_TOOLS = [
    // ===== 对话聊天 =====
    {
        name: 'ChatGPT',
        desc: 'OpenAI 出品的对话式 AI，支持文本生成、代码编写、翻译、问答等多种任务',
        category: 'chat',
        url: 'https://chat.openai.com',
        icon: '🤖',
        rating: 4.8,
        price: 'freemium',
        tags: ['对话', 'GPT-4o', '多模态'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Claude',
        desc: 'Anthropic 推出的 AI 助手，擅长长文本分析、代码编写和深度推理',
        category: 'chat',
        url: 'https://claude.ai',
        icon: '🧠',
        rating: 4.7,
        price: 'freemium',
        tags: ['对话', '长文本', '推理'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Gemini',
        desc: 'Google 推出的多模态 AI，支持文本、图片、视频理解和生成',
        category: 'chat',
        url: 'https://gemini.google.com',
        icon: '💎',
        rating: 4.5,
        price: 'freemium',
        tags: ['Google', '多模态', '搜索'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Kimi',
        desc: '月之暗面出品，支持 20 万字超长上下文，擅长文档分析和信息整理',
        category: 'chat',
        url: 'https://kimi.moonshot.cn',
        icon: '🌙',
        rating: 4.4,
        price: 'free',
        tags: ['长文本', '中文', '文档分析'],
        isNew: false,
        isHot: true,
    },
    {
        name: '豆包',
        desc: '字节跳动推出的 AI 助手，支持对话、写作、翻译等，中文体验优秀',
        category: 'chat',
        url: 'https://www.doubao.com',
        icon: '🫘',
        rating: 4.3,
        price: 'free',
        tags: ['中文', '字节', '多功能'],
        isNew: false,
    },
    {
        name: 'DeepSeek',
        desc: '深度求索推出的开源大模型，推理能力强，支持 API 调用，性价比极高',
        category: 'chat',
        url: 'https://chat.deepseek.com',
        icon: '🔮',
        rating: 4.6,
        price: 'free',
        tags: ['开源', '推理', '性价比'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Perplexity',
        desc: 'AI 搜索引擎，实时联网搜索并给出带引用来源的回答',
        category: 'chat',
        url: 'https://www.perplexity.ai',
        icon: '🔎',
        rating: 4.5,
        price: 'freemium',
        tags: ['搜索', '实时', '引用'],
        isNew: false,
    },
    {
        name: 'Poe',
        desc: 'Quora 推出的 AI 聚合平台，一个入口访问 ChatGPT、Claude、Gemini 等多个模型',
        category: 'chat',
        url: 'https://poe.com',
        icon: '⚔️',
        rating: 4.2,
        price: 'freemium',
        tags: ['聚合', '多模型', '对比'],
        isNew: false,
    },

    // ===== 写作文案 =====
    {
        name: 'Notion AI',
        desc: '集成在 Notion 中的 AI 写作助手，支持生成、润色、翻译、总结等',
        category: 'writing',
        url: 'https://www.notion.so/product/ai',
        icon: '📝',
        rating: 4.5,
        price: 'freemium',
        tags: ['笔记', '写作', '协作'],
        isNew: false,
    },
    {
        name: 'Jasper',
        desc: '专业的 AI 营销文案工具，支持广告文案、博客、社交媒体内容生成',
        category: 'writing',
        url: 'https://www.jasper.ai',
        icon: '✨',
        rating: 4.3,
        price: 'paid',
        tags: ['营销', '文案', '品牌'],
        isNew: false,
    },
    {
        name: 'Copy.ai',
        desc: 'AI 文案生成器，快速生成营销文案、邮件、社交媒体帖子等',
        category: 'writing',
        url: 'https://www.copy.ai',
        icon: '📋',
        rating: 4.2,
        price: 'freemium',
        tags: ['文案', '营销', '模板'],
        isNew: false,
    },
    {
        name: '秘塔写作猫',
        desc: '中文 AI 写作助手，支持论文降重、文章改写、语法纠错',
        category: 'writing',
        url: 'https://xiezuocat.com',
        icon: '🐱',
        rating: 4.1,
        price: 'freemium',
        tags: ['中文', '论文', '改写'],
        isNew: false,
    },
    {
        name: 'Grammarly',
        desc: '英文写作辅助工具，AI 驱动的语法检查、风格优化和改写建议',
        category: 'writing',
        url: 'https://www.grammarly.com',
        icon: '📖',
        rating: 4.6,
        price: 'freemium',
        tags: ['英文', '语法', '润色'],
        isNew: false,
    },

    // ===== 图像生成 =====
    {
        name: 'Midjourney',
        desc: '顶级 AI 绘画工具，通过文字描述生成高质量艺术图片',
        category: 'image',
        url: 'https://www.midjourney.com',
        icon: '🎨',
        rating: 4.9,
        price: 'paid',
        tags: ['绘画', '艺术', '高质量'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'DALL·E 3',
        desc: 'OpenAI 的图像生成模型，集成在 ChatGPT 中，理解力强，生成精准',
        category: 'image',
        url: 'https://openai.com/dall-e-3',
        icon: '🖼️',
        rating: 4.6,
        price: 'freemium',
        tags: ['OpenAI', '文生图', '精准'],
        isNew: false,
    },
    {
        name: 'Stable Diffusion',
        desc: '开源图像生成模型，可本地部署，社区生态丰富，自定义程度高',
        category: 'image',
        url: 'https://stability.ai',
        icon: '🌀',
        rating: 4.5,
        price: 'free',
        tags: ['开源', '本地部署', '自定义'],
        isNew: false,
    },
    {
        name: '即梦 AI',
        desc: '字节跳动推出的 AI 创作平台，支持文生图、图生图，中文提示词友好',
        category: 'image',
        url: 'https://jimeng.jianying.com',
        icon: '💭',
        rating: 4.3,
        price: 'free',
        tags: ['中文', '字节', '创作'],
        isNew: false,
    },
    {
        name: 'Leonardo.ai',
        desc: '专业级 AI 图像生成平台，适合游戏美术、概念设计等场景',
        category: 'image',
        url: 'https://leonardo.ai',
        icon: '🎭',
        rating: 4.4,
        price: 'freemium',
        tags: ['游戏', '美术', '专业'],
        isNew: false,
    },
    {
        name: 'Remove.bg',
        desc: 'AI 一键去除图片背景，速度快效果好，支持批量处理',
        category: 'image',
        url: 'https://www.remove.bg',
        icon: '✂️',
        rating: 4.5,
        price: 'freemium',
        tags: ['去背景', '抠图', '批量'],
        isNew: false,
    },

    // ===== 视频制作 =====
    {
        name: 'Sora',
        desc: 'OpenAI 的文生视频模型，可生成长达 60 秒的高质量视频',
        category: 'video',
        url: 'https://openai.com/sora',
        icon: '🎥',
        rating: 4.7,
        price: 'paid',
        tags: ['文生视频', 'OpenAI', '高质量'],
        isNew: true,
        isHot: true,
    },
    {
        name: 'Runway',
        desc: '专业 AI 视频编辑平台，支持文生视频、视频特效、绿幕去除等',
        category: 'video',
        url: 'https://runwayml.com',
        icon: '🎬',
        rating: 4.5,
        price: 'freemium',
        tags: ['视频编辑', '特效', 'Gen-3'],
        isNew: false,
    },
    {
        name: 'Pika',
        desc: '简单易用的 AI 视频生成工具，支持文生视频和图生视频',
        category: 'video',
        url: 'https://pika.art',
        icon: '⚡',
        rating: 4.3,
        price: 'freemium',
        tags: ['视频生成', '简单', '创意'],
        isNew: false,
    },
    {
        name: 'HeyGen',
        desc: 'AI 数字人视频生成，支持多语言口播、视频翻译、虚拟主播',
        category: 'video',
        url: 'https://www.heygen.com',
        icon: '🧑‍💼',
        rating: 4.4,
        price: 'freemium',
        tags: ['数字人', '口播', '翻译'],
        isNew: false,
    },
    {
        name: '可灵 AI',
        desc: '快手推出的视频生成大模型，支持文生视频、图生视频，效果惊艳',
        category: 'video',
        url: 'https://kling.kuaishou.com',
        icon: '🎞️',
        rating: 4.5,
        price: 'free',
        tags: ['快手', '中文', '视频生成'],
        isNew: true,
        isHot: true,
    },

    // ===== 音频音乐 =====
    {
        name: 'Suno',
        desc: 'AI 音乐生成神器，输入文字描述即可生成完整歌曲（含人声）',
        category: 'audio',
        url: 'https://suno.com',
        icon: '🎶',
        rating: 4.7,
        price: 'freemium',
        tags: ['音乐', '歌曲', '人声'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Udio',
        desc: 'AI 音乐创作平台，音质出色，支持多种音乐风格和自定义歌词',
        category: 'audio',
        url: 'https://www.udio.com',
        icon: '🎸',
        rating: 4.5,
        price: 'freemium',
        tags: ['音乐', '高音质', '风格'],
        isNew: false,
    },
    {
        name: 'ElevenLabs',
        desc: '最逼真的 AI 语音合成，支持声音克隆、多语言配音',
        category: 'audio',
        url: 'https://elevenlabs.io',
        icon: '🗣️',
        rating: 4.6,
        price: 'freemium',
        tags: ['语音', '克隆', '配音'],
        isNew: false,
    },
    {
        name: '网易天音',
        desc: '网易出品的 AI 音乐创作平台，中文歌曲生成效果好',
        category: 'audio',
        url: 'https://tianyin.163.com',
        icon: '🎹',
        rating: 4.1,
        price: 'free',
        tags: ['中文', '网易', '作曲'],
        isNew: false,
    },

    // ===== 编程开发 =====
    {
        name: 'GitHub Copilot',
        desc: 'AI 编程助手，实时代码补全和建议，支持几乎所有编程语言',
        category: 'coding',
        url: 'https://github.com/features/copilot',
        icon: '🤝',
        rating: 4.7,
        price: 'paid',
        tags: ['代码补全', 'GitHub', '多语言'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Cursor',
        desc: '内置 AI 的代码编辑器，支持对话式编程、代码生成和重构',
        category: 'coding',
        url: 'https://cursor.sh',
        icon: '🖱️',
        rating: 4.6,
        price: 'freemium',
        tags: ['编辑器', '对话编程', '重构'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Kiro',
        desc: 'AI IDE，规范驱动开发，自动生成需求文档和任务列表，支持 Agent Hooks',
        category: 'coding',
        url: 'https://kiro.dev',
        icon: '⚡',
        rating: 4.8,
        price: 'freemium',
        tags: ['IDE', '规范驱动', 'Agent'],
        isNew: true,
        isHot: true,
    },
    {
        name: 'Replit',
        desc: '在线 IDE + AI 编程助手，支持多语言在线编写、运行和部署',
        category: 'coding',
        url: 'https://replit.com',
        icon: '💻',
        rating: 4.3,
        price: 'freemium',
        tags: ['在线IDE', '部署', '协作'],
        isNew: false,
    },
    {
        name: 'v0.dev',
        desc: 'Vercel 推出的 AI 前端生成工具，描述需求即可生成 React 组件',
        category: 'coding',
        url: 'https://v0.dev',
        icon: '🔺',
        rating: 4.4,
        price: 'freemium',
        tags: ['前端', 'React', 'UI生成'],
        isNew: false,
    },

    // ===== 设计工具 =====
    {
        name: 'Canva AI',
        desc: '集成 AI 功能的在线设计平台，一键生成海报、PPT、社交媒体图片',
        category: 'design',
        url: 'https://www.canva.com',
        icon: '🎨',
        rating: 4.5,
        price: 'freemium',
        tags: ['设计', '海报', 'PPT'],
        isNew: false,
    },
    {
        name: '即时设计 AI',
        desc: '国产在线设计工具，AI 生成 UI 设计稿，支持 Figma 文件导入',
        category: 'design',
        url: 'https://js.design',
        icon: '✏️',
        rating: 4.2,
        price: 'freemium',
        tags: ['UI设计', '国产', 'Figma'],
        isNew: false,
    },
    {
        name: 'Figma AI',
        desc: 'Figma 内置 AI 功能，支持自动布局、设计建议和原型生成',
        category: 'design',
        url: 'https://www.figma.com',
        icon: '🖌️',
        rating: 4.6,
        price: 'freemium',
        tags: ['UI', '协作', '原型'],
        isNew: true,
    },
    {
        name: 'Looka',
        desc: 'AI Logo 设计工具，输入品牌名和偏好即可生成专业 Logo',
        category: 'design',
        url: 'https://looka.com',
        icon: '💎',
        rating: 4.1,
        price: 'freemium',
        tags: ['Logo', '品牌', '快速'],
        isNew: false,
    },

    // ===== 效率办公 =====
    {
        name: '通义千问',
        desc: '阿里云推出的 AI 助手，支持文档分析、表格处理、PPT 生成等办公场景',
        category: 'productivity',
        url: 'https://tongyi.aliyun.com',
        icon: '🔮',
        rating: 4.3,
        price: 'free',
        tags: ['阿里', '办公', '文档'],
        isNew: false,
    },
    {
        name: 'Gamma',
        desc: 'AI 一键生成精美 PPT/文档/网页，告别排版烦恼',
        category: 'productivity',
        url: 'https://gamma.app',
        icon: '📊',
        rating: 4.5,
        price: 'freemium',
        tags: ['PPT', '文档', '演示'],
        isNew: false,
        isHot: true,
    },
    {
        name: 'Otter.ai',
        desc: 'AI 会议记录工具，实时语音转文字，自动生成会议摘要',
        category: 'productivity',
        url: 'https://otter.ai',
        icon: '🦦',
        rating: 4.3,
        price: 'freemium',
        tags: ['会议', '转录', '摘要'],
        isNew: false,
    },
    {
        name: 'Dify',
        desc: '开源 LLM 应用开发平台，可视化编排 AI 工作流，快速构建 AI 应用',
        category: 'productivity',
        url: 'https://dify.ai',
        icon: '🔧',
        rating: 4.4,
        price: 'freemium',
        tags: ['开源', '工作流', '开发'],
        isNew: false,
    },

    // ===== 学习教育 =====
    {
        name: 'Khan Academy AI',
        desc: '可汗学院的 AI 导师 Khanmigo，个性化辅导数学、编程等学科',
        category: 'education',
        url: 'https://www.khanacademy.org',
        icon: '🎓',
        rating: 4.4,
        price: 'free',
        tags: ['教育', '辅导', '数学'],
        isNew: false,
    },
    {
        name: 'Duolingo Max',
        desc: 'AI 驱动的语言学习，支持角色扮演对话和智能纠错',
        category: 'education',
        url: 'https://www.duolingo.com',
        icon: '🦉',
        rating: 4.5,
        price: 'freemium',
        tags: ['语言', '学习', '互动'],
        isNew: false,
    },
    {
        name: 'Consensus',
        desc: 'AI 学术搜索引擎，从 2 亿篇论文中提取研究结论',
        category: 'education',
        url: 'https://consensus.app',
        icon: '🔬',
        rating: 4.3,
        price: 'freemium',
        tags: ['学术', '论文', '研究'],
        isNew: false,
    },

    // ===== 营销推广 =====
    {
        name: 'AdCreative.ai',
        desc: 'AI 广告创意生成，自动生成高转化率的广告图片和文案',
        category: 'marketing',
        url: 'https://www.adcreative.ai',
        icon: '📢',
        rating: 4.2,
        price: 'paid',
        tags: ['广告', '创意', '转化'],
        isNew: false,
    },
    {
        name: 'Synthesia',
        desc: 'AI 视频营销工具，用虚拟人物生成多语言营销视频',
        category: 'marketing',
        url: 'https://www.synthesia.io',
        icon: '🎭',
        rating: 4.3,
        price: 'paid',
        tags: ['视频', '数字人', '多语言'],
        isNew: false,
    },
    {
        name: 'Brandmark',
        desc: 'AI 品牌设计工具，自动生成 Logo、配色方案和品牌指南',
        category: 'marketing',
        url: 'https://brandmark.io',
        icon: '🏷️',
        rating: 4.0,
        price: 'paid',
        tags: ['品牌', 'Logo', '配色'],
        isNew: false,
    },
];
