// Sticker emoji list
const STICKERS = [
  '⭐','🌟','✨','💫','🔥','❤️','💜','💙','🌈','🎉',
  '🎊','🎈','🌸','🌺','🌻','🍀','🦋','🌙','☀️','⚡',
  '💎','👑','🎯','🎨','🎭','🎪','🦄','🐉','🌊','🏔️',
  '🍭','🍬','🎂','🍕','🌮','☕','🍜','🎵','🎶','📸',
];

// Theme presets
const THEMES = [
  {
    name: '赛博朋克',
    sub: '霓虹 · 未来感',
    color: '#ff00ff',
    filter: 'hue-rotate(270deg) saturate(2) contrast(1.3) brightness(0.9)',
    textColor: '#00ffff',
    sticker: '⚡',
  },
  {
    name: '日系胶片',
    sub: '复古 · 温柔',
    color: '#f4a261',
    filter: 'sepia(50%) contrast(1.1) brightness(1.05) saturate(0.9)',
    textColor: '#fff8f0',
    sticker: '🌸',
  },
  {
    name: '极简黑白',
    sub: '简约 · 高级',
    color: '#ffffff',
    filter: 'grayscale(100%) contrast(1.2)',
    textColor: '#ffffff',
    sticker: '◼',
  },
  {
    name: '梦幻紫',
    sub: '浪漫 · 梦幻',
    color: '#a78bfa',
    filter: 'hue-rotate(240deg) saturate(1.5) brightness(1.1)',
    textColor: '#e9d5ff',
    sticker: '🦄',
  },
  {
    name: '夏日橙',
    sub: '活力 · 阳光',
    color: '#fb923c',
    filter: 'hue-rotate(-20deg) saturate(1.6) brightness(1.1) contrast(1.1)',
    textColor: '#fff7ed',
    sticker: '☀️',
  },
  {
    name: '深海蓝',
    sub: '沉静 · 神秘',
    color: '#38bdf8',
    filter: 'hue-rotate(200deg) saturate(1.4) brightness(0.95) contrast(1.1)',
    textColor: '#e0f2fe',
    sticker: '🌊',
  },
  {
    name: '森林绿',
    sub: '自然 · 清新',
    color: '#4ade80',
    filter: 'hue-rotate(100deg) saturate(1.3) brightness(1.05) contrast(1.05)',
    textColor: '#dcfce7',
    sticker: '🍀',
  },
  {
    name: '暗夜红',
    sub: '热烈 · 戏剧',
    color: '#f43f5e',
    filter: 'hue-rotate(-10deg) saturate(1.8) contrast(1.3) brightness(0.85)',
    textColor: '#ffe4e6',
    sticker: '🔥',
  },
  {
    name: '奶油白',
    sub: '柔和 · 清新',
    color: '#fef3c7',
    filter: 'brightness(1.15) saturate(0.7) contrast(0.9) sepia(15%)',
    textColor: '#78350f',
    sticker: '🌻',
  },
  {
    name: '极光',
    sub: '绚丽 · 梦境',
    color: '#06b6d4',
    filter: 'hue-rotate(160deg) saturate(1.8) brightness(1.05) contrast(1.15)',
    textColor: '#cffafe',
    sticker: '🌈',
  },
  {
    name: '黄金时代',
    sub: '奢华 · 复古',
    color: '#f59e0b',
    filter: 'sepia(40%) hue-rotate(10deg) saturate(1.4) contrast(1.15) brightness(1.05)',
    textColor: '#fef3c7',
    sticker: '👑',
  },
  {
    name: '午夜',
    sub: '深邃 · 冷峻',
    color: '#6366f1',
    filter: 'brightness(0.75) contrast(1.3) saturate(0.8) hue-rotate(220deg)',
    textColor: '#c7d2fe',
    sticker: '🌙',
  },
];
