/* ======================================================================
   椰子英语乐园 · 数据层 (data.js)
   - THEMES: 主题分组与单词
   - ALPHABET: A-Z 字母及代表词
   图标只存 key，渲染时用 getIcon(key) 取 SVG（见 icons.js）。
   ====================================================================== */

/* ---------------------- 主题与单词 ---------------------- */
const THEMES = [
  {
    id: 'animals',
    name: '小动物',
    en: 'Animals',
    icon: 'cat',
    words: [
      { icon: 'cat',      en: 'Cat',      zh: '猫' },
      { icon: 'dog',      en: 'Dog',      zh: '狗' },
      { icon: 'rabbit',   en: 'Rabbit',   zh: '兔子' },
      { icon: 'bear',     en: 'Bear',     zh: '熊' },
      { icon: 'fish',     en: 'Fish',     zh: '鱼' },
      { icon: 'bird',     en: 'Bird',     zh: '小鸟' },
      { icon: 'pig',      en: 'Pig',      zh: '小猪' },
      { icon: 'lion',     en: 'Lion',     zh: '狮子' },
      { icon: 'zebra',    en: 'Zebra',    zh: '斑马' },
      { icon: 'duck',     en: 'Duck',     zh: '鸭子' },
      { icon: 'frog',     en: 'Frog',     zh: '青蛙' },
      { icon: 'elephant', en: 'Elephant', zh: '大象' },
      { icon: 'monkey',   en: 'Monkey',   zh: '猴子' },
      { icon: 'tiger',    en: 'Tiger',    zh: '老虎' },
      { icon: 'cow',      en: 'Cow',      zh: '奶牛' },
      { icon: 'sheep',    en: 'Sheep',    zh: '绵羊' },
      { icon: 'horse',    en: 'Horse',    zh: '马' },
      { icon: 'mouse',    en: 'Mouse',    zh: '老鼠' },
      { icon: 'owl',      en: 'Owl',      zh: '猫头鹰' },
      { icon: 'panda',    en: 'Panda',    zh: '熊猫' },
    ],
  },
  {
    id: 'fruits',
    name: '水果',
    en: 'Fruits',
    icon: 'apple',
    words: [
      { icon: 'apple',      en: 'Apple',      zh: '苹果' },
      { icon: 'banana',     en: 'Banana',     zh: '香蕉' },
      { icon: 'grape',      en: 'Grapes',     zh: '葡萄' },
      { icon: 'orange',     en: 'Orange',     zh: '橙子' },
      { icon: 'strawberry', en: 'Strawberry', zh: '草莓' },
      { icon: 'watermelon', en: 'Watermelon', zh: '西瓜' },
      { icon: 'pear',       en: 'Pear',       zh: '梨' },
      { icon: 'cherry',     en: 'Cherry',     zh: '樱桃' },
      { icon: 'peach',      en: 'Peach',      zh: '桃子' },
      { icon: 'lemon',      en: 'Lemon',      zh: '柠檬' },
      { icon: 'pineapple',  en: 'Pineapple',  zh: '菠萝' },
      { icon: 'mango',      en: 'Mango',      zh: '芒果' },
      { icon: 'kiwi',       en: 'Kiwi',       zh: '猕猴桃' },
      { icon: 'coconut',    en: 'Coconut',    zh: '椰子' },
      { icon: 'blueberry',  en: 'Blueberry',  zh: '蓝莓' },
    ],
  },
  {
    id: 'colors',
    name: '颜色',
    en: 'Colors',
    icon: 'color_red',
    words: [
      { icon: 'color_red',    en: 'Red',    zh: '红色' },
      { icon: 'color_yellow', en: 'Yellow', zh: '黄色' },
      { icon: 'color_blue',   en: 'Blue',   zh: '蓝色' },
      { icon: 'color_green',  en: 'Green',  zh: '绿色' },
      { icon: 'color_purple', en: 'Purple', zh: '紫色' },
      { icon: 'color_orange', en: 'Orange', zh: '橙色' },
      { icon: 'color_pink',   en: 'Pink',   zh: '粉色' },
      { icon: 'color_brown',  en: 'Brown',  zh: '棕色' },
      { icon: 'color_black',  en: 'Black',  zh: '黑色' },
      { icon: 'color_white',  en: 'White',  zh: '白色' },
      { icon: 'color_gray',   en: 'Gray',   zh: '灰色' },
      { icon: 'color_skyblue',en: 'Sky blue', zh: '天蓝色' },
      { icon: 'color_lime',   en: 'Lime',   zh: '青柠色' },
      { icon: 'color_gold',   en: 'Gold',   zh: '金色' },
    ],
  },
  {
    id: 'numbers',
    name: '数字',
    en: 'Numbers',
    icon: 'num_1',
    words: [
      { icon: 'num_1',  en: 'One',   zh: '一' },
      { icon: 'num_2',  en: 'Two',   zh: '二' },
      { icon: 'num_3',  en: 'Three', zh: '三' },
      { icon: 'num_4',  en: 'Four',  zh: '四' },
      { icon: 'num_5',  en: 'Five',  zh: '五' },
      { icon: 'num_6',  en: 'Six',   zh: '六' },
      { icon: 'num_7',  en: 'Seven', zh: '七' },
      { icon: 'num_8',  en: 'Eight', zh: '八' },
      { icon: 'num_9',  en: 'Nine',  zh: '九' },
      { icon: 'num_10', en: 'Ten',   zh: '十' },
      { icon: 'num_11', en: 'Eleven',    zh: '十一' },
      { icon: 'num_12', en: 'Twelve',    zh: '十二' },
      { icon: 'num_13', en: 'Thirteen',  zh: '十三' },
      { icon: 'num_14', en: 'Fourteen',  zh: '十四' },
      { icon: 'num_15', en: 'Fifteen',   zh: '十五' },
      { icon: 'num_16', en: 'Sixteen',   zh: '十六' },
      { icon: 'num_17', en: 'Seventeen', zh: '十七' },
      { icon: 'num_18', en: 'Eighteen',  zh: '十八' },
      { icon: 'num_19', en: 'Nineteen',  zh: '十九' },
      { icon: 'num_20', en: 'Twenty',    zh: '二十' },
    ],
  },
  {
    id: 'shapes',
    name: '形状',
    en: 'Shapes',
    icon: 'shape_star',
    words: [
      { icon: 'shape_circle',   en: 'Circle',   zh: '圆形' },
      { icon: 'shape_square',   en: 'Square',   zh: '正方形' },
      { icon: 'shape_triangle', en: 'Triangle', zh: '三角形' },
      { icon: 'shape_star',     en: 'Star',     zh: '星形' },
      { icon: 'shape_heart',    en: 'Heart',    zh: '爱心' },
      { icon: 'shape_diamond',  en: 'Diamond',  zh: '菱形' },
      { icon: 'shape_oval',     en: 'Oval',     zh: '椭圆' },
      { icon: 'shape_rect',     en: 'Rectangle',zh: '长方形' },
      { icon: 'shape_pentagon', en: 'Pentagon', zh: '五边形' },
      { icon: 'shape_hexagon',  en: 'Hexagon',  zh: '六边形' },
      { icon: 'shape_crescent', en: 'Crescent', zh: '月牙形' },
      { icon: 'shape_arrow',    en: 'Arrow',    zh: '箭头' },
    ],
  },
  {
    id: 'transport',
    name: '交通工具',
    en: 'Transport',
    icon: 'car',
    words: [
      { icon: 'car',   en: 'Car',   zh: '汽车' },
      { icon: 'bus',   en: 'Bus',   zh: '公交车' },
      { icon: 'train', en: 'Train', zh: '火车' },
      { icon: 'plane', en: 'Plane', zh: '飞机' },
      { icon: 'boat',  en: 'Boat',  zh: '船' },
      { icon: 'bike',  en: 'Bike',  zh: '自行车' },
      { icon: 'van',   en: 'Van',   zh: '货车' },
      { icon: 'truck', en: 'Truck', zh: '卡车' },
      { icon: 'rocket',en: 'Rocket',zh: '火箭' },
      { icon: 'helicopter', en: 'Helicopter', zh: '直升机' },
      { icon: 'taxi',  en: 'Taxi',  zh: '出租车' },
      { icon: 'scooter', en: 'Scooter', zh: '滑板车' },
      { icon: 'police_car', en: 'Police car', zh: '警车' },
    ],
  },
  {
    id: 'family',
    name: '家庭与身体',
    en: 'Family & Body',
    icon: 'mom',
    words: [
      { icon: 'mom',  en: 'Mom',  zh: '妈妈' },
      { icon: 'dad',  en: 'Dad',  zh: '爸爸' },
      { icon: 'baby', en: 'Baby', zh: '宝宝' },
      { icon: 'hand', en: 'Hand', zh: '手' },
      { icon: 'eye',  en: 'Eye',  zh: '眼睛' },
      { icon: 'foot', en: 'Foot', zh: '脚' },
      { icon: 'grandma2', en: 'Grandma', zh: '奶奶' },
      { icon: 'grandpa2', en: 'Grandpa', zh: '爷爷' },
      { icon: 'boy',  en: 'Boy',  zh: '男孩' },
      { icon: 'girl', en: 'Girl', zh: '女孩' },
      { icon: 'ear',  en: 'Ear',  zh: '耳朵' },
      { icon: 'nose', en: 'Nose', zh: '鼻子' },
      { icon: 'mouth',en: 'Mouth',zh: '嘴巴' },
    ],
  },
  {
    id: 'food',
    name: '食物',
    en: 'Food',
    icon: 'cake',
    words: [
      { icon: 'bread',    en: 'Bread',     zh: '面包' },
      { icon: 'milk',     en: 'Milk',      zh: '牛奶' },
      { icon: 'cake',     en: 'Cake',      zh: '蛋糕' },
      { icon: 'cookie',   en: 'Cookie',    zh: '饼干' },
      { icon: 'candy',    en: 'Candy',     zh: '糖果' },
      { icon: 'egg2',     en: 'Egg',       zh: '鸡蛋' },
      { icon: 'icecream', en: 'Ice cream', zh: '冰淇淋' },
      { icon: 'juice',    en: 'Juice',     zh: '果汁' },
      { icon: 'pizza',    en: 'Pizza',     zh: '披萨' },
      { icon: 'burger',   en: 'Burger',    zh: '汉堡' },
      { icon: 'carrot',   en: 'Carrot',    zh: '胡萝卜' },
      { icon: 'corn',     en: 'Corn',      zh: '玉米' },
      { icon: 'rice',     en: 'Rice',      zh: '米饭' },
      { icon: 'fish_food',en: 'Fish',      zh: '鱼' },
    ],
  },
  {
    id: 'nature',
    name: '自然与天气',
    en: 'Nature & Weather',
    icon: 'sun',
    words: [
      { icon: 'sun',    en: 'Sun',    zh: '太阳' },
      { icon: 'moon',   en: 'Moon',   zh: '月亮' },
      { icon: 'star',   en: 'Star',   zh: '星星' },
      { icon: 'cloud',  en: 'Cloud',  zh: '云' },
      { icon: 'rain',   en: 'Rain',   zh: '雨' },
      { icon: 'snow',   en: 'Snow',   zh: '雪' },
      { icon: 'tree',   en: 'Tree',   zh: '树' },
      { icon: 'flower', en: 'Flower', zh: '花' },
      { icon: 'leaf',   en: 'Leaf',   zh: '叶子' },
      { icon: 'rainbow',en: 'Rainbow',zh: '彩虹' },
      { icon: 'mountain',en: 'Mountain', zh: '山' },
      { icon: 'water',  en: 'Water',  zh: '水' },
      { icon: 'fire',   en: 'Fire',   zh: '火' },
      { icon: 'wind',   en: 'Wind',   zh: '风' },
    ],
  },
  {
    id: 'clothes',
    name: '衣物',
    en: 'Clothes',
    icon: 'shirt',
    words: [
      { icon: 'shirt', en: 'Shirt', zh: '衬衫' },
      { icon: 'pants', en: 'Pants', zh: '裤子' },
      { icon: 'dress', en: 'Dress', zh: '裙子' },
      { icon: 'shoe',  en: 'Shoes', zh: '鞋子' },
      { icon: 'sock',  en: 'Socks', zh: '袜子' },
      { icon: 'hat',   en: 'Hat',   zh: '帽子' },
      { icon: 'coat',  en: 'Coat',  zh: '外套' },
      { icon: 'scarf', en: 'Scarf', zh: '围巾' },
      { icon: 'gloves',en: 'Gloves',zh: '手套' },
      { icon: 'boots', en: 'Boots', zh: '靴子' },
      { icon: 'shorts',en: 'Shorts',zh: '短裤' },
      { icon: 'cap',   en: 'Cap',   zh: '鸭舌帽' },
    ],
  },
  {
    id: 'toys',
    name: '玩具',
    en: 'Toys',
    icon: 'teddy',
    words: [
      { icon: 'ball',   en: 'Ball',  zh: '球' },
      { icon: 'teddy',  en: 'Teddy', zh: '泰迪熊' },
      { icon: 'blocks', en: 'Blocks',zh: '积木' },
      { icon: 'book',   en: 'Book',  zh: '书' },
      { icon: 'drum',   en: 'Drum',  zh: '鼓' },
      { icon: 'kite',   en: 'Kite',  zh: '风筝' },
      { icon: 'balloon',en: 'Balloon',zh: '气球' },
      { icon: 'car_toy',en: 'Toy car',zh: '玩具车' },
      { icon: 'robot',  en: 'Robot', zh: '机器人' },
      { icon: 'doll',   en: 'Doll',  zh: '娃娃' },
      { icon: 'top',    en: 'Top',   zh: '陀螺' },
      { icon: 'yoyo',   en: 'Yo-yo', zh: '溜溜球' },
    ],
  },
  {
    id: 'jobs',
    name: '职业',
    en: 'Jobs',
    icon: 'doctor',
    words: [
      { icon: 'doctor',      en: 'Doctor',      zh: '医生' },
      { icon: 'teacher',     en: 'Teacher',     zh: '老师' },
      { icon: 'police',      en: 'Police',      zh: '警察' },
      { icon: 'chef',        en: 'Chef',        zh: '厨师' },
      { icon: 'firefighter', en: 'Firefighter', zh: '消防员' },
      { icon: 'farmer',      en: 'Farmer',      zh: '农民' },
      { icon: 'pilot',       en: 'Pilot',       zh: '飞行员' },
      { icon: 'nurse',       en: 'Nurse',       zh: '护士' },
      { icon: 'singer',      en: 'Singer',      zh: '歌手' },
      { icon: 'painter',     en: 'Painter',     zh: '画家' },
    ],
  },
  {
    id: 'instruments',
    name: '乐器',
    en: 'Instruments',
    icon: 'guitar',
    words: [
      { icon: 'guitar',    en: 'Guitar',    zh: '吉他' },
      { icon: 'piano',     en: 'Piano',     zh: '钢琴' },
      { icon: 'trumpet',   en: 'Trumpet',   zh: '小号' },
      { icon: 'violin',    en: 'Violin',    zh: '小提琴' },
      { icon: 'xylophone', en: 'Xylophone', zh: '木琴' },
      { icon: 'drum',      en: 'Drum',      zh: '鼓' },
      { icon: 'flute',     en: 'Flute',     zh: '长笛' },
      { icon: 'saxophone', en: 'Saxophone', zh: '萨克斯' },
      { icon: 'harp',      en: 'Harp',      zh: '竖琴' },
      { icon: 'maracas',   en: 'Maracas',   zh: '沙锤' },
      { icon: 'bell',      en: 'Bell',      zh: '铃铛' },
    ],
  },
  {
    id: 'room',
    name: '房间物品',
    en: 'Room',
    icon: 'bed',
    words: [
      { icon: 'bed',    en: 'Bed',    zh: '床' },
      { icon: 'chair',  en: 'Chair',  zh: '椅子' },
      { icon: 'table',  en: 'Table',  zh: '桌子' },
      { icon: 'lamp',   en: 'Lamp',   zh: '台灯' },
      { icon: 'clock',  en: 'Clock',  zh: '时钟' },
      { icon: 'door',   en: 'Door',   zh: '门' },
      { icon: 'window', en: 'Window', zh: '窗户' },
      { icon: 'sofa',   en: 'Sofa',   zh: '沙发' },
      { icon: 'tv',     en: 'TV',     zh: '电视' },
      { icon: 'mirror', en: 'Mirror', zh: '镜子' },
      { icon: 'cup',    en: 'Cup',    zh: '杯子' },
      { icon: 'plate',  en: 'Plate',  zh: '盘子' },
      { icon: 'fridge', en: 'Fridge', zh: '冰箱' },
      { icon: 'key',    en: 'Key',    zh: '钥匙' },
    ],
  },
];

/* ---------------------- 字母 A-Z ---------------------- */
const ALPHABET = [
  { letter: 'A', word: 'Apple',     zh: '苹果',   icon: 'apple' },
  { letter: 'B', word: 'Bear',      zh: '熊',     icon: 'bear' },
  { letter: 'C', word: 'Cat',       zh: '猫',     icon: 'cat' },
  { letter: 'D', word: 'Dog',       zh: '狗',     icon: 'dog' },
  { letter: 'E', word: 'Egg',       zh: '鸡蛋',   icon: 'egg' },
  { letter: 'F', word: 'Fish',      zh: '鱼',     icon: 'fish' },
  { letter: 'G', word: 'Grapes',    zh: '葡萄',   icon: 'grape' },
  { letter: 'H', word: 'Hat',       zh: '帽子',   icon: 'hat' },
  { letter: 'I', word: 'Ice cream', zh: '冰淇淋', icon: 'icecream' },
  { letter: 'J', word: 'Juice',     zh: '果汁',   icon: 'juice' },
  { letter: 'K', word: 'Kite',      zh: '风筝',   icon: 'kite' },
  { letter: 'L', word: 'Lion',      zh: '狮子',   icon: 'lion' },
  { letter: 'M', word: 'Moon',      zh: '月亮',   icon: 'moon' },
  { letter: 'N', word: 'Nest',      zh: '鸟窝',   icon: 'bird' },
  { letter: 'O', word: 'Orange',    zh: '橙子',   icon: 'orange' },
  { letter: 'P', word: 'Pig',       zh: '小猪',   icon: 'pig' },
  { letter: 'Q', word: 'Queen',     zh: '女王',   icon: 'crown' },
  { letter: 'R', word: 'Rabbit',    zh: '兔子',   icon: 'rabbit' },
  { letter: 'S', word: 'Sun',       zh: '太阳',   icon: 'sun' },
  { letter: 'T', word: 'Tree',      zh: '树',     icon: 'tree' },
  { letter: 'U', word: 'Umbrella',  zh: '雨伞',   icon: 'umbrella' },
  { letter: 'V', word: 'Van',       zh: '货车',   icon: 'van' },
  { letter: 'W', word: 'Watermelon',zh: '西瓜',   icon: 'watermelon' },
  { letter: 'X', word: 'Box',       zh: '盒子',   icon: 'box' },
  { letter: 'Y', word: 'Yellow',    zh: '黄色',   icon: 'color_yellow' },
  { letter: 'Z', word: 'Zebra',     zh: '斑马',   icon: 'zebra' },
];
